LOG_DIR = "./logs/"

DEMO_NUM_SAMPLES_DEFAULT = 4
DEMO_SEED_DEFAULT = 0
DEMO_OUT_DEFAULT = "demo.png"
DEMO_LEVELS = ["Excellent", "Good", "Fair", "Poor", "Bad"]
DEMO_PRED_COLOR = "steelblue"
DEMO_GT_COLOR = "coral"

TRAIN_SAMPLE_SEED_DEFAULT = 42

TRAIN_STEPS_DEFAULT = 500
TRAIN_WARMUP_STEPS_DEFAULT = 5
TRAIN_BATCH_SIZE_DEFAULT = 4
TRAIN_LR_DEFAULT = 1e-3
TRAIN_GRAD_ACCUM_DEFAULT = 32
TRAIN_LOG_EVERY_DEFAULT = 5
TRAIN_OSC_THRESHOLD_DEFAULT = 0.3
TRAIN_OSC_FACTOR_DEFAULT = 0.5
TRAIN_OSC_COOLDOWN_DEFAULT = 50
TRAIN_OSC_MIN_LR_DEFAULT = 1e-6
TRAIN_BACKBONE_LR_SCALE_DEFAULT = 1.0
TRAIN_FREEZE_BACKBONE_DEFAULT = False

MODEL_TYPES = ("vit", "cnn")
TRAIN_MODEL_TYPE_DEFAULT = "vit"
